#define CONFIG_BT_BLUEDROID_ENABLED TRUE
#define CONFIG_BT_BTC_TASK_STACK_SIZE 3072
#define CONFIG_BT_CLASSIC_ENABLED TRUE
#define CONFIG_BT_ENC_KEY_SIZE_CTRL_STD TRUE
#define CONFIG_BT_A2DP_ENABLE TRUE
#define CONFIG_BT_AVRCP_ENABLED TRUE
#define CONFIG_BT_AVRCP_CT_COVER_ART_ENABLED TRUE
#define CONFIG_BT_SDP_PAD_LEN 300
#define CONFIG_BT_SDP_ATTR_LEN 300
#define CONFIG_BT_GOEPC_ENABLED TRUE
#define CONFIG_BT_STACK_NO_LOG TRUE // TODO: actually wire up logs
/*
#define CONFIG_BT_LOG_HCI_TRACE_LEVEL 2
#define CONFIG_BT_LOG_BTM_TRACE_LEVEL 2
#define CONFIG_BT_LOG_L2CAP_TRACE_LEVEL 2
#define CONFIG_BT_LOG_RFCOMM_TRACE_LEVEL 2
#define CONFIG_BT_LOG_SDP_TRACE_LEVEL 2
#define CONFIG_BT_LOG_GAP_TRACE_LEVEL 2
#define CONFIG_BT_LOG_BNEP_TRACE_LEVEL 2
#define CONFIG_BT_LOG_PAN_TRACE_LEVEL 2
#define CONFIG_BT_LOG_A2D_TRACE_LEVEL 2
#define CONFIG_BT_LOG_AVDT_TRACE_LEVEL 2
#define CONFIG_BT_LOG_AVCT_TRACE_LEVEL 2
#define CONFIG_BT_LOG_AVRC_TRACE_LEVEL 2
#define CONFIG_BT_LOG_MCA_TRACE_LEVEL 2
#define CONFIG_BT_LOG_HID_TRACE_LEVEL 2
#define CONFIG_BT_LOG_APPL_TRACE_LEVEL 2
#define CONFIG_BT_LOG_GATT_TRACE_LEVEL 2
#define CONFIG_BT_LOG_SMP_TRACE_LEVEL 2
#define CONFIG_BT_LOG_BTIF_TRACE_LEVEL 2
#define CONFIG_BT_LOG_BTC_TRACE_LEVEL 2
#define CONFIG_BT_LOG_OSI_TRACE_LEVEL 2
#define CONFIG_BT_LOG_BLUFI_TRACE_LEVEL 2
*/
#define CONFIG_BT_ACL_CONNECTIONS 4
#define CONFIG_BT_SMP_ENABLE TRUE
#define CONFIG_BT_SMP_MAX_BONDS 15
#define CONFIG_BT_MAX_DEVICE_NAME_LEN 32

#define BT_TASK_EXTRA_STACK_SIZE 512

#define CONFIG_BT_SMP_CRYPTO_STACK_NATIVE TRUE