#!/usr/bin/env python3
import sys

if len(sys.argv) < 2:
    print("USAGE: tools/hcd2c.py <firmware.hcd>")
    exit(1)

FILENAME = sys.argv[1]

print(f"// Autogenerated from {FILENAME} by hcd2c.py")
print("#include <stdint.h>")
print("#include <stdlib.h>")
print("")
print("uint8_t *hcd_init_commands[] = {")
with open(FILENAME, "rb") as f:
    while len(buf := f.read(3)) > 0:
        buf += f.read(buf[2])
        print("    (uint8_t[]) {0x01, " + ", ".join([f"0x{x:02X}" for x in buf]) + "},")
print("    NULL,")
print("};")