#!/usr/bin/env python3
import sys

if len(sys.argv) < 2:
    print("USAGE: tools/hcd2c.py <firmware.hcd>")
    exit(1)

FILENAME = sys.argv[1]

lines = []

with open(FILENAME, "rb") as f:
    while len(buf := f.read(3)) > 0:
        buf += f.read(buf[2])
        lines.append("    (uint8_t[]) {0x01, " + ", ".join([f"0x{x:02X}" for x in buf]) + "},")

print(f"// Autogenerated from {FILENAME} by hcd2c.py")
print(f"#include <stdint.h>\n")
print(f"#define HCD_NUM_INIT_COMMANDS {len(lines)}")
print("\nuint8_t *hcd_init_commands[HCD_NUM_INIT_COMMANDS] = {")
print("\n".join(lines))
print("};")